---
- hosts: localhost
  connection: local 
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: myansiblelatestbucket
      aws_access_key: AKIAZOGSWYVYDJ7ZRJKV
      aws_secret_key: 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
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: poojanewbucket
         type: example
  - s3_bucket:
      name: myansiblelatestbucket
      policy: "{{ lookup('file','policy.json') }}"
      requester_pays: yes
      versioning: yes
      tags:
        example: tag1
        another: tag2
