---
- hosts: localhost
  tasks:
  - name: Create an S3 bucket
    become: true
    aws_s3: aws_access_key=AKIAZOGSWYVYFIPZ7LVJ* aws_secret_key=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* bucket=testbuck  mode=create permission=public-read region=ap-south-1
