---
- hosts: localhost
  connection: local 
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: poojanewbucket
      aws_access_key: AKIAZOGSWYVYFIPZ7LVJ
      aws_secret_key: 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
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: poojanewbucket
         type: example
  - amazon.aws.s3_bucket:
    name: mys3bucket
    state: present
    public_access:
        block_public_acls: true
        ignore_public_acls: true
        ## keys == 'false' can be omitted, undefined keys defaults to 'false'
        # block_public_policy: false
        # restrict_public_buckets: false
