---
- hosts: localhost
  connection: local 
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: dellbucket
      aws_access_key: AKIAZOGSWYVYCOSQ6DCY
      aws_secret_key: GEUQq+7HmUqmHqpNETgcOS2UIe4DjLQUx3PEYKv9
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: dellbucket
         type: example
