---
- hosts: localhost
  connection: local 
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: myansiblelatestbucket
      aws_access_key: AKIAZOGSWYVYDJ7ZRJKV
      aws_secret_key: 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
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: myansiblelatestbucket
         type: example
  - amazon.aws.s3_bucket:
     name: ansibleS3bucket
     state: present
     public_access:
       block_public_acls: true
       ignore_public_acls: true
        ## keys == 'false' can be omitted, undefined keys defaults to 'false'
        # block_public_policy: false
        # restrict_public_buckets: false
