---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: myansiblebucket
      aws_access_key: AKIAZOGSWYVYFIPZ7LVJ 
      aws_secret_key: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 
      policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
      state: present
      region: ap-south-1
      permission=public-read
      versioning: no
      tags:
         name: myansiblebucket
         type: example
         my_bucket_policy.json
{
  "Id": "Policyxxx",
  "Statement": [
    {
      "Action": [
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::myansiblebucket/*",
      "Principal": {
        "AWS": [
          "*"
        ]
      }
    }
  ]
}
